=== Lilyana7/MountainsCatalogXML2024/mountain.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mountainsCatalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="highMountains">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mountain" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:short" name="height"/>
                    <xs:element type="xs:string" name="highestPeak"/>
                    <xs:element type="xs:string" name="region"/>
                    <xs:element type="xs:string" name="type"/>
                    <xs:element type="xs:string" name="description"/>
                    <xs:element name="site">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="href" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                  <xs:attribute type="xs:float" name="latitude" use="optional"/>
                  <xs:attribute type="xs:float" name="longitude" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mediumMountains">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mountain" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:short" name="height"/>
                    <xs:element type="xs:string" name="highestPeak"/>
                    <xs:element type="xs:string" name="region"/>
                    <xs:element type="xs:string" name="type"/>
                    <xs:element type="xs:string" name="description"/>
                    <xs:element name="site">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="href" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                  <xs:attribute type="xs:float" name="latitude" use="optional"/>
                  <xs:attribute type="xs:float" name="longitude" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lowMountains">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mountain" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:short" name="height"/>
                    <xs:element type="xs:string" name="highestPeak"/>
                    <xs:element type="xs:string" name="region"/>
                    <xs:element type="xs:string" name="type"/>
                    <xs:element type="xs:string" name="description"/>
                    <xs:element name="site">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="href" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                  <xs:attribute type="xs:float" name="latitude" use="optional"/>
                  <xs:attribute type="xs:float" name="longitude" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Lilyana7/MountainsCatalogXML2024/mountain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mountainsCatalog [
  <!ENTITY website "https://bg.wikipedia.org/wiki/">
]>
<?xml-stylesheet type="text/xsl" href="mountain.xsl"?>
<mountainsCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="mountain.xsd">
 <highMountains>
    <mountain id="1" latitude="42.1354" longitude="23.3004">
      <name>РИЛА</name>
      <height>2925</height>
      <highestPeak>Мусала</highestPeak>
      <region>Югозападен</region>
      <type>Младонагъната</type>
      <description>Рила е най-високата планина в България и на целия Балкански полуостров.Най-старото име на планината е Доункас, дадено и от траките. Означава място 
с много вода. Тракийско е и другото и име - Роула, което славяните видоизменят на Рила.То също е свързано с многоводието на планината (означава “водна планина”).
Това название не е случайно - в Рила има около 200 езера и множество минерални извори. От тук извират едни от най – пълноводните и дълги реки на Балканите. Някои 
по-известните забележителности са връх Мальовица, Национален парк Рила, Рилски манастир, Седемте Рилски езера и Стобските земни пирамиди.</description>
      <site href="&website;Рила">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
   <mountain id="2" latitude="41.46" longitude="23.24">
      <name>ПИРИН</name>
      <height>2914</height>
      <highestPeak>Вихрен</highestPeak>
      <region>Югозападен</region>
      <type>Младонагъната</type>
      <description>Пирин е втората по височина планина в България. Най-старото познато име на планината е Орбелус - белоснежна, познато ни от траките, докато 
славяните са я наричали Перин или Перун. Българите традиционно смятат, че името на Пирин идва от това на славянския бог Перун – повелителят на гръмотевиците. 
По-сериозните изследвания обаче показват, че имената Пирин и Перун съвпадат чисто случайно и името на Пирин идва от тракийската дума “перинтос”, което означава скала,
която пък идва от хетската "перунаш". Някои от по-известните забележителности са Байкушевата мура, Бъндеришки езера, връх Вихрен, връх Синаница, Национален парк 
Пирин.</description>
      <site href="&website;Пирин">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
   <mountain id="3" latitude="42.47" longitude="19.25">
      <name>СТАРА ПЛАНИНА</name>
      <height>2376</height>
      <highestPeak>Ботев</highestPeak>
      <region>Централен</region>
      <type>Младонагъната</type>
      <description>Стара планина се простира по цялата дължина на България и разделя страната на Северна и Южна България. Нарича се още Балкан, откъдето произлиза и 
името на Балканския полуостров. Древното римско име на Стара планина е Хемус. Стара планина се разделя на три дяла: западен, среден и източен. Някои от по-известните 
забележителности са водопад Видимско пръскало, водопад Райско пръскало, връх Ботев, връх Бузлуджа, връх Шипка, природен парк Централен Балкан.</description>
      <site href="&website;Стара планина">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
   <mountain id="4" latitude="41.6011" longitude="24.5742">
      <name>РОДОПИ</name>
      <height>2191</height>
      <highestPeak>Голям Перелик</highestPeak>
      <region>Южен</region>
      <type>Старонагъната</type>
      <description>Родопите е най-обширната планина в България и заема около една седма част от българската територия. Името на планината Родопи е с тракийски произход.
Род-опа се тълкува като първоначално име на река със значение „ръждива/червеникава вода“. Някои от по-известните забележителности са връх Голям Перелик,Дяволски мост
Пещера Ухловица, Триградското ждрело, Чудните мостове.</description>
      <site href="&website;Родопи">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
</highMountains>
<mediumMountains>
   <mountain id="5" latitude="43.235" longitude="23.9104">
      <name>ВИТОША</name>
      <height>2290</height>
      <highestPeak>Черни връх</highestPeak>
      <region>Югозападен</region>
      <type>Младонагъната</type>
      <description>Витоша е планината, която се радва на най-големия поток от туристи в нашата страна. Там е и първата проява на организиран туризъм у нас, подбудена 
от родолюбивият Алеко Константинов. Някои от по-известните забележителностите, които се намират там са Боянски водопад, Драгалевски манастир, Златните мостове,
Природен парк Витоша, Черни връх.</description>
      <site href="&website;Витоша">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
   <mountain id="6" latitude="41.1354" longitude="22.304">
      <name>БЕЛАСИЦА</name>
      <height>2029</height>
      <highestPeak>Радомир</highestPeak>
      <region>Югозападен</region>
      <type>Старонагъната</type>
      <description>Беласица е планина в областта Македония. Тя е част от Осоговско-Беласишката планинска група. Понастоящем е поделена между Гърция (около 45%),
 Република Македония (около 35%) и България (около 20%). От двете гръцки имена Керкини е предполагаемото антично име, а Белес е модерното, произлязло от българското.
Някои от по-известните забележителностите, които се намират там са връх Радомир, Самуиловата крепост и връх Тумба.</description>
      <site href="&website;Беласица">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
</mediumMountains>
<lowMountains>
   <mountain id="7" latitude="40.14" longitude="21.34">
      <name>СЛАВЯНКА</name>
      <height>2212</height>
      <highestPeak>Гоцев връх</highestPeak>
      <region>Югозападен</region>
      <type>Младонагъната</type>
      <description>Славянка е планина, разположена на границата между България и Гърция. Тя е част от Рило-Родопския масив. По билото на Славянка минава държавната 
граница между България и Гърция, като по-голяма част от площтта ѝ се намира на българска територия. Някои от по-известните забележителностите, които се намират там са 
връх Гоцев връх и резерватът Алиботуш.</description>
      <site href="&website;Славянка">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
   <mountain id="8" latitude="44.134" longitude="24.04">
      <name>СТРАНДЖА</name>
      <height>710</height>
      <highestPeak>Голямо градище</highestPeak>
      <region>Югоизточен</region>
      <type>Старонагъната</type>
      <description>Странджа заема площ от около 10000 кв. км. на територията на югоизточна България и северната част на европейска Турция. У нас се намират само 
северните и североизточните й разклонения, които имат хълмисто-нископланински характер и са силно разчленени от сравнително гъста долинна мрежа. По-голямата и 
по-висока част на планината е разположена в Турция, като най-високият й връх Голяма Махиада (1031 м) е в турска територия. Някои от по-известните забележителностите, 
които се намират там са Братанова пещера, Природен парк Странджа, Резерват Силкосия.</description>
      <site href="&website;Странджа">https://bg.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BB%D0%B0</site>
   </mountain>
</lowMountains>
</mountainsCatalog>
